name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: SCCoPilotApp
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build release artifacts
      run: ./gradlew assembleRelease
    - name: Push artifacts
      run: |
        mkdir downloads
        cp app/build/outputs/apk/release/app-release-unsigned.apk downloads/
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
          name: release-apk
          path: SCCoPilotApp/downloads

