name: Full Release

on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: Game
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make Gradle executable
        working-directory: Game
        run: chmod +x ./gradlew
      - name: Build Release APK
        working-directory: Game
        run: ./gradlew assembleRelease
      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: SCCoPilotApp/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/$EXPORT_NAME.zip
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux/X11" build/linux/$EXPORT_NAME.x86_64
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows Desktop" build/windows/$EXPORT_NAME.exe
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          artifacts: "release-apk, Game/build/*,${{ steps.sign_app }}"
          token: ${{ secrets.GITHUB_TOKEN }}
