name: Full Release

on:
  push:
    tags:
    - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with: 
        artifacts: "release-apk, linux, mac, windows"
        token: ${{ secrets.GITHUB_TOKEN }}
